### ISSUE TITLE
Add netstandard 2.1 Support

### ISSUE THREAD

**Issue by KiarashS** [cloudscribe/cloudscribe.Web.Pagination#55]
Cloudscribe Web Pagination doesn't support `netstandard 2.1`. If you reference Cloudscribe Web Pagination 3 in a `netstandard 2.1` class library, you get to this error:

`Package cloudscribe.Web.Pagination 3.0.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package cloudscribe.Web.Pagination 3.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)`

**Comment by joeaudette** [comment]
right because it depends on asp.net core 3 which requires netcoreapp3.0 and a framework reference
https://andrewlock.net/converting-a-netstandard-2-library-to-netcore-3/

you can use the older 2.x version  of our nuget which is netstandard2.0 if you like.
https://www.nuget.org/packages/cloudscribe.Web.Pagination/
